"""
Vault Manager - Silver Tier
Enhanced vault management with approval tracking.
"""

from pathlib import Path
from datetime import datetime
import json


class VaultManager:
    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.inbox = self.vault_path / 'Inbox'
        self.needs_action = self.vault_path / 'Needs_Action'
        self.pending_approval = self.vault_path / 'Pending_Approval'
        self.approved = self.vault_path / 'Approved'
        self.plans = self.vault_path / 'Plans'
        self.done = self.vault_path / 'Done'
        self.logs = self.vault_path / 'Logs'
        self.dashboard = self.vault_path / 'Dashboard.md'
        
        # Ensure folders exist
        for folder in [self.inbox, self.needs_action, self.pending_approval, 
                       self.approved, self.plans, self.done, self.logs]:
            folder.mkdir(parents=True, exist_ok=True)
    
    def log_action(self, action_type: str, details: dict, status: str = 'success'):
        """Log an action to the Logs folder"""
        today = datetime.now().strftime('%Y-%m-%d')
        log_file = self.logs / f'{today}.json'
        
        log_entry = {
            'timestamp': datetime.now().isoformat(),
            'action_type': action_type,
            'details': details,
            'status': status,
            'actor': 'claude_code_silver',
            'tier': 'silver'
        }
        
        # Append to log file
        if log_file.exists():
            try:
                logs = json.loads(log_file.read_text(encoding='utf-8'))
            except:
                logs = []
        else:
            logs = []
        
        logs.append(log_entry)
        log_file.write_text(json.dumps(logs, indent=2), encoding='utf-8')
    
    def get_stats(self) -> dict:
        """Get current vault stats"""
        return {
            'inbox': len(list(self.inbox.iterdir())) if self.inbox.exists() else 0,
            'needs_action': len(list(self.needs_action.iterdir())) if self.needs_action.exists() else 0,
            'pending_approval': len(list(self.pending_approval.glob('*.md'))) if self.pending_approval.exists() else 0,
            'approved': len(list(self.approved.iterdir())) if self.approved.exists() else 0,
            'plans': len(list(self.plans.iterdir())) if self.plans.exists() else 0,
            'done': len(list(self.done.iterdir())) if self.done.exists() else 0
        }
    
    def update_dashboard(self):
        """Update Dashboard.md with current stats"""
        stats = self.get_stats()
        
        dashboard_content = f'''# 📊 AI Employee Dashboard - Silver Tier

---
last_updated: {datetime.now().isoformat()}
status: active
tier: silver
---

## Overview
Your AI Employee is running in **Silver Tier** mode with multiple watchers and approval workflow.

## Active Watchers
| Watcher | Status | Check Interval |
|---------|--------|----------------|
| Gmail | ✅ Active | 2 minutes |
| WhatsApp | ✅ Active | 30 seconds |

## Quick Stats
| Metric | Value |
|--------|-------|
| Items in Inbox | {stats['inbox']} |
| Items in Needs_Action | {stats['needs_action']} |
| Pending Approval | {stats['pending_approval']} |
| Approved | {stats['approved']} |
| Plans Created | {stats['plans']} |
| Completed Tasks | {stats['done']} |

## Recent Activity
<!-- Check /Logs/ folder for full audit trail -->

---
*Generated by AI Employee v0.2 - Silver Tier*
'''
        
        self.dashboard.write_text(dashboard_content, encoding='utf-8')
        return stats
