"""
Claude Code Integration Script - Bronze Tier
Helps Claude Code read from and write to the vault.
Run this with: claude "Process Needs_Action folder"
"""

from pathlib import Path
from datetime import datetime
import json


class VaultManager:
    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.needs_action = self.vault_path / 'Needs_Action'
        self.done = self.vault_path / 'Done'
        self.plans = self.vault_path / 'Plans'
        self.logs = self.vault_path / 'Logs'
        self.dashboard = self.vault_path / 'Dashboard.md'
        
        # Ensure folders exist
        for folder in [self.needs_action, self.done, self.plans, self.logs]:
            folder.mkdir(parents=True, exist_ok=True)
    
    def get_pending_items(self) -> list:
        """Get all items in Needs_Action folder"""
        items = []
        for file in self.needs_action.iterdir():
            if file.is_file() and file.suffix == '.md':
                content = file.read_text(encoding='utf-8')
                items.append({
                    'file': file,
                    'name': file.name,
                    'content': content
                })
        return items
    
    def create_plan(self, title: str, steps: list, source_file: str = None) -> Path:
        """Create a plan file for Claude to follow"""
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        plan_filename = f'PLAN_{title.replace(" ", "_")}_{timestamp}.md'
        
        steps_md = '\n'.join([f'- [ ] {step}' for step in steps])
        
        plan_content = f'''---
type: plan
created: {datetime.now().isoformat()}
status: pending
source: {source_file or 'manual'}
---

# {title}

## Steps
{steps_md}

## Notes
<!-- Add your analysis and notes here -->

## Completion
When all steps are done, move this file to /Done/ folder.
'''
        
        plan_path = self.plans / plan_filename
        plan_path.write_text(plan_content, encoding='utf-8')
        return plan_path
    
    def log_action(self, action_type: str, details: dict, status: str = 'success'):
        """Log an action to the Logs folder"""
        today = datetime.now().strftime('%Y-%m-%d')
        log_file = self.logs / f'{today}.json'
        
        log_entry = {
            'timestamp': datetime.now().isoformat(),
            'action_type': action_type,
            'details': details,
            'status': status,
            'actor': 'claude_code_bronze'
        }
        
        # Append to log file
        if log_file.exists():
            logs = json.loads(log_file.read_text(encoding='utf-8'))
        else:
            logs = []
        
        logs.append(log_entry)
        log_file.write_text(json.dumps(logs, indent=2), encoding='utf-8')
    
    def move_to_done(self, file_path: Path):
        """Move a file from Needs_Action to Done"""
        if file_path.exists():
            dest = self.done / file_path.name
            file_path.rename(dest)
            self.log_action('move_to_done', {'file': file_path.name})
    
    def update_dashboard(self, pending_count: int, done_count: int):
        """Update Dashboard.md with current stats"""
        dashboard_content = f'''# 📊 AI Employee Dashboard

---
last_updated: {datetime.now().isoformat()}
status: active
tier: bronze
---

## Overview
Your personal AI employee is running in Bronze Tier mode.

## Quick Stats
| Metric | Value |
|--------|-------|
| Items Pending | {pending_count} |
| Items Completed | {done_count} |
| Mode | Manual (Bronze) |

## Pending Items
<!-- Check /Needs_Action/ folder for details -->

## Recent Activity
<!-- Check /Logs/ folder for full audit trail -->

---
*Generated by AI Employee v0.1 - Bronze Tier*
'''
        self.dashboard.write_text(dashboard_content, encoding='utf-8')
    
    def get_stats(self) -> dict:
        """Get current vault stats"""
        pending = len(list(self.needs_action.glob('*.md')))
        done = len(list(self.done.glob('*.md')))
        plans = len(list(self.plans.glob('*.md')))
        
        return {
            'pending': pending,
            'done': done,
            'plans': plans
        }


if __name__ == '__main__':
    vault_path = Path(__file__).parent.parent
    
    manager = VaultManager(vault_path=str(vault_path))
    stats = manager.get_stats()
    
    print('\n📊 Vault Statistics:')
    print(f'  Pending items: {stats["pending"]}')
    print(f'  Completed items: {stats["done"]}')
    print(f'  Active plans: {stats["plans"]}')
    print(f'\n📁 Vault path: {vault_path}')
